### ISSUE TITLE
problem loading aladin.js

### ISSUE THREAD

**Issue by volodymyrss** [esg-epfl-apc/galaxy#2]
When trying to use FITS visualization I get 404 for this:

http://localhost:8080/static/plugins/visualizations/fits_image_viewer/static/dist/aladin-lite-galaxy/aladin.js

on revision 13e0ed77a0e54c3d4e3536d67a223a9339dc0452 , the latest.

It's similar to #1  but not the same it seems.
What could it be?

**Comment by francoismg** [comment]
It's weird cause they have tested it last week and it was working for them so there shouldn't be so much differences between the latest and the one they tested it on. I will try to clone the latest from dev to test it on my side

When you run run.sh does it says that it detected changes in fits_image_viewer?
Do run.sh or make client output some errors when you run them?
Do you only get that error or are the other js and css files missing too?
Also does aladin-lite get copied to "plugin"/static or is it just missing from  galaxy/static, if it's only missing from galaxy/static the problem likely comes from gulp and there should be some kind of error when running run.sh or make client

**Comment by volodymyrss** [comment]
> It's weird cause they have tested it last week and it was working for them so there shouldn't be so much differences between the latest and the one they tested it on. I will try to clone the latest from dev to test it on my side
> 
> When you run run.sh does it says that it detected changes in fits_image_viewer? Do run.sh or make client output some errors when you run them? 

I do not see any message like that.
The only error is `Error reading tool from path: phenotype_association/sift.xml` unrelated presumably.

> Do you only get that error or are the other js and css files missing too?

Only aladin.js, everything else is good. This is different from #1 

What's weird it works on one laptop but not another.

Could we build a container with a live version, including everything installed, so we are sure we are looking on the same thing?

**Comment by francoismg** [comment]
You should see something like that when running run.sh with either "No changes detected....." or "Changes detected building plugin (something like that)" if you don't see any of that it might be cause it's skipping the client build which might be why the plugin isn't built correctly 

[18:37:38] Using gulpfile ~/Documents/GitHub/galaxy/client/gulpfile.js
[18:37:38] Starting 'default'...
[18:37:38] Starting 'fonts'...
[18:37:38] Starting 'stageLibs'...
[18:37:38] Starting 'buildPlugins'...
[18:37:38] Finished 'stageLibs' after 9.98 ms
[18:37:38] Finished 'buildPlugins' after 12 ms
[18:37:38] Starting 'cleanPlugins'...
[18:37:38] Finished 'fonts' after 16 ms
.....
No changes detected for editor
No changes detected for example
No changes detected for fits_image_viewer
No changes detected for h5web
No changes detected for heatmap_default
.....
[18:37:38] Finished 'cleanPlugins' after 398 ms
[18:37:38] Starting 'stagePlugins'...
[18:37:38] Finished 'stagePlugins' after 395 ms
[18:37:38] Finished 'default' after 806 ms

In the previous issue I said that sometimes it would skip client build for no particular reason so maybe that's the problem. It could also be some node related problem if it doesn't load the aladin lite dependency but then it wouldn't load parcel and the script.js wouldn't be built so I don't think it's that.

Have you tried to run "make client" to force a client rebuild before running run.sh?

Do you see the dist folder in the "plugin"/static folder? It's different from the main /static folder the template is linking to.

Sometimes you can have some disparities even on the same machine with the same build from two different installs so not sure that it will resolve all these problems but I was already looking into making a container. If by live version you mean prod version it's another thing but I can look into that too and it should be useful anyway.
